import BaseSeeder from "@ioc:Adonis/Lucid/Seeder";
import User from "App/Models/User";
import { Roles } from "App/Services/Utils/Enums";

export default class extends BaseSeeder {
  public async run() {
    const uniqueEmail = "email";

    await User.fetchOrCreateMany(uniqueEmail, [
      {
        name: "João Silva",
        email: "joao.silva@gmail.com",
        password: "senha123",
        cpf: "11111111111",
        phone: "1111111111",
        sector: "Setor A",
        role: Roles.OPERATOR,
      },
      {
        name: "Maria Santos",
        email: "maria.santos@gmail.com",
        password: "senha456",
        cpf: "22222222222",
        phone: "2222222222",
        sector: "Setor B",
        role: Roles.OPERATOR,
      },
      {
        name: "Pedro Oliveira",
        email: "pedro.oliveira@gmail.com",
        password: "senha789",
        cpf: "33333333333",
        phone: "3333333333",
        sector: "Setor C",
        role: Roles.OPERATOR,
      },
      {
        name: "Ana Costa",
        email: "ana.costa@gmail.com",
        password: "senhaabc",
        cpf: "44444444444",
        phone: "4444444444",
        sector: "Setor D",
        role: Roles.OPERATOR,
      },
      {
        name: "Lucas Santos",
        email: "lucas.santos@gmail.com",
        password: "senha123",
        cpf: "55555555555",
        phone: "5555555555",
        sector: "Setor E",
        role: Roles.OPERATOR,
      },
      {
        name: "Fernanda Oliveira",
        email: "fernanda.oliveira@gmail.com",
        password: "senha456",
        cpf: "66666666666",
        phone: "6666666666",
        sector: "Setor F",
        role: Roles.OPERATOR,
      },
      {
        name: "Rafaela Costa",
        email: "rafaela.costa@gmail.com",
        password: "senha789",
        cpf: "77777777777",
        phone: "7777777777",
        sector: "Setor G",
        role: Roles.OPERATOR,
      },
      {
        name: "Gustavo Silva",
        email: "gustavo.silva@gmail.com",
        password: "senhaabc",
        cpf: "88888888888",
        phone: "8888888888",
        sector: "Setor H",
        role: Roles.OPERATOR,
      },
      {
        name: "Carolina Santos",
        email: "carolina.santos@gmail.com",
        password: "senha123",
        cpf: "99999999999",
        phone: "9999999999",
        sector: "Setor I",
        role: Roles.OPERATOR,
      },
      {
        name: "Marina Silva",
        email: "marina.silva@gmail.com",
        password: "senha789",
        cpf: "45454545454",
        phone: "4545454545",
        sector: "Setor K",
        role: Roles.OPERATOR,
      },
      {
        name: "Gustavo Oliveira",
        email: "gustavo.oliveira@gmail.com",
        password: "senha123",
        cpf: "78787878787",
        phone: "7878787878",
        sector: "Setor M",
        role: Roles.OPERATOR,
      },
      {
        name: "Carla Santos",
        email: "carla.santos@gmail.com",
        password: "senha456",
        cpf: "98989898989",
        phone: "9898989898",
        sector: "Setor N",
        role: Roles.OPERATOR,
      },
      {
        name: "Lucas Costa",
        email: "lucas.costa@gmail.com",
        password: "senhaabc",
        cpf: "22233344455",
        phone: "2223334445",
        sector: "Setor O",
        role: Roles.OPERATOR,
      },
      {
        name: "Isabela Silva",
        email: "isabela.silva@gmail.com",
        password: "senha123",
        cpf: "66677788899",
        phone: "6667778889",
        sector: "Setor P",
        role: Roles.OPERATOR,
      },
      {
        name: "Pedro Santos",
        email: "pedro.santos@gmail.com",
        password: "senha456",
        cpf: "11122233344",
        phone: "1112223334",
        sector: "Setor Q",
        role: Roles.OPERATOR,
      },
      {
        name: "Laura Costa",
        email: "laura.costa@gmail.com",
        password: "senha789",
        cpf: "77788899911",
        phone: "7778889991",
        sector: "Setor R",
        role: Roles.OPERATOR,
      },
      {
        name: "Matheus Oliveira",
        email: "matheus.oliveira@gmail.com",
        password: "senhaabc",
        cpf: "55544433322",
        phone: "5554443332",
        sector: "Setor S",
        role: Roles.OPERATOR,
      },
      {
        name: "Ana Silva",
        email: "ana.silva@gmail.com",
        password: "senha123",
        cpf: "99988877766",
        phone: "9998887776",
        sector: "Setor T",
        role: Roles.OPERATOR,
      },
      {
        name: "Rafael Costa",
        email: "rafael.costa@gmail.com",
        password: "senha456",
        cpf: "44433322211",
        phone: "4443332221",
        sector: "Setor U",
        role: Roles.OPERATOR,
      },
    ]);
  }
}
