import BaseSeeder from "@ioc:Adonis/Lucid/Seeder";
import Location from "App/Models/Location";

export default class extends BaseSeeder {
  public async run() {
    const uniqueRoom = "room";

    await Location.fetchOrCreateMany(uniqueRoom, [
      {
        room: "101",
        floor: 1,
        block: "A",
        description: "AUDITÓRIO",
      },
      {
        room: "102",
        floor: 1,
        block: "A",
        description: "CEDIDA PARA RESTAURANTE UNIVERSITÁRIO",
      },
      {
        room: "103",
        floor: 1,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "104",
        floor: 1,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "105",
        floor: 1,
        block: "A",
        description: "CANTINA",
      },
      {
        room: "201",
        floor: 2,
        block: "A",
        description: "APOIO CADM",
      },
      {
        room: "202",
        floor: 2,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "203",
        floor: 2,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "204",
        floor: 2,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "205",
        floor: 2,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "206",
        floor: 2,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "207",
        floor: 2,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "208",
        floor: 2,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "209",
        floor: 2,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "210",
        floor: 2,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "211",
        floor: 2,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "212",
        floor: 2,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "301",
        floor: 3,
        block: "A",
        description: "APOIO CADM",
      },
      {
        room: "302",
        floor: 3,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "303",
        floor: 3,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "304",
        floor: 3,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "305",
        floor: 3,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "306",
        floor: 3,
        block: "A",
        description: "SALA DO PET",
      },
      {
        room: "307",
        floor: 3,
        block: "A",
        description: "MINIAUDITÓRIO",
      },
      {
        room: "308",
        floor: 3,
        block: "A",
        description: "SALA DE MONITORIA",
      },
      {
        room: "309",
        floor: 3,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "310",
        floor: 3,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "311",
        floor: 3,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "312",
        floor: 3,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "313",
        floor: 3,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "314",
        floor: 3,
        block: "A",
        description: "SALA DE AULA",
      },
      {
        room: "101",
        floor: 1,
        block: "B",
        description: "DEPEX",
      },
      {
        room: "102",
        floor: 1,
        block: "B",
        description: "SALA DE AULA",
      },
      {
        room: "103",
        floor: 1,
        block: "B",
        description: "ALMOXARIFADO GPMM",
      },
      {
        room: "104",
        floor: 1,
        block: "B",
        description: "GERÊNCIA DE PATRIMÔNIO",
      },
      {
        room: "105",
        floor: 1,
        block: "B",
        description: "MANUTENÇÃO DE AR CONDICIONADO",
      },
      {
        room: "201",
        floor: 2,
        block: "B",
        description: "COORDENAÇÃO ACADÊMICA",
      },
      {
        room: "202",
        floor: 2,
        block: "B",
        description: "DIREÇÃO E COORDENAÇÃO ADMINISTRATIVA",
      },
      {
        room: "203",
        floor: 2,
        block: "B",
        description: "SALA DAS GERÊNCIAS",
      },
      {
        room: "204",
        floor: 2,
        block: "B",
        description: "COPA CADM",
      },
      {
        room: "205",
        floor: 2,
        block: "B",
        description: "SALA CEDIDA PARA EMPRESA TERCEIRIZADA",
      },
      {
        room: "101",
        floor: 1,
        block: "C",
        description: "DEPÓSITO DE REGENTES E VIDRARIAS",
      },
      {
        room: "102",
        floor: 1,
        block: "C",
        description: "LABORATÓRIO DE PRODUÇÃO - NETGI",
      },
      {
        room: "103",
        floor: 1,
        block: "C",
        description: "COPA - CEDIDA PARA EMPRESA TERCEIRIZADA",
      },
      {
        room: "104",
        floor: 1,
        block: "C",
        description: "DEPÓSITO GPMM",
      },
      {
        room: "105",
        floor: 1,
        block: "C",
        description: "DEPÓSITO GPMM",
      },
      {
        room: "106",
        floor: 1,
        block: "C",
        description: "DEPÓSITO GPMM",
      },
      {
        room: "-",
        floor: 1,
        block: "C",
        description: "PÁTIO BLOCO C",
      },
      {
        room: "201",
        floor: 2,
        block: "C",
        description: "LABORATÓRIO DE PRODUÇÃO III",
      },
      {
        room: "202",
        floor: 2,
        block: "C",
        description: "LABORATÓRIO DE PRODUÇÃO IV",
      },
      {
        room: "203",
        floor: 2,
        block: "C",
        description: "COPA TÉCNICOS",
      },
      {
        room: "204",
        floor: 2,
        block: "C",
        description: "LABORATÓRIO MULTIÁREA I",
      },
      {
        room: "205",
        floor: 2,
        block: "C",
        description: "LABORATÓRIO MULTIÁREA II",
      },
      {
        room: "206",
        floor: 2,
        block: "C",
        description: "LABORATÓRIO DE PRODUÇÃO",
      },
      {
        room: "207",
        floor: 2,
        block: "C",
        description: "LABORATÓRIO DE NEGÓCIOS",
      },
      {
        room: "101",
        floor: 1,
        block: "D",
        description: "LABORATÓRIO DE FARMÁCIA I",
      },
      {
        room: "102",
        floor: 1,
        block: "D",
        description: "LABORATÓRIO DE FARMÁCIA II",
      },
      {
        room: "103 A",
        floor: 1,
        block: "D",
        description: "SALA DE AULA",
      },
      {
        room: "103 B",
        floor: 1,
        block: "D",
        description: "SALA DOS TÉCNICOS",
      },
      {
        room: "104",
        floor: 1,
        block: "D",
        description: "LABORATÓRIO DE FARMÁCIA III",
      },
      {
        room: "105",
        floor: 1,
        block: "D",
        description: "LABORATÓRIO DE FARMÁCIA IV",
      },
      {
        room: "106",
        floor: 1,
        block: "D",
        description: "LABORATÓRIO DE FARMÁCIA V",
      },
      {
        room: "107",
        floor: 1,
        block: "D",
        description: "LABORATÓRIO DE INFORMÁTICA ",
      },
      {
        room: "108",
        floor: 1,
        block: "D",
        description: "LABORATÓRIO DE FARMÁCIA VI",
      },
      {
        room: "109",
        floor: 1,
        block: "D",
        description: "LABORATÓRIO DE FARMÁCIA VII ",
      },
      {
        room: "110",
        floor: 1,
        block: "D",
        description: "LABORATÓRIO DE FARMÁCIA VIII",
      },
      {
        room: "111",
        floor: 1,
        block: "D",
        description: "LABORATÓRIO DE FARMÁCIA IX",
      },
      {
        room: "112",
        floor: 1,
        block: "D",
        description: "LABORATÓRIO DE FARMÁCIA X",
      },
      {
        room: "113",
        floor: 1,
        block: "D",
        description: "SALA QUENTE",
      },
      {
        room: "201",
        floor: 2,
        block: "D",
        description: "LABORATÓRIO DE PEDAGOGIA I",
      },
      {
        room: "202",
        floor: 2,
        block: "D",
        description: "LABORATÓRIO DE BIOLOGIA I",
      },
      {
        room: "203",
        floor: 2,
        block: "D",
        description: "LABORATÓRIO DE BIOLOGIA II",
      },
      {
        room: "204",
        floor: 2,
        block: "D",
        description: "LABORATÓRIO DE BIOLOGIA III ",
      },
      {
        room: "205",
        floor: 2,
        block: "D",
        description: "LABORATÓRIO DE BIOLOGIA IV",
      },
      {
        room: "206",
        floor: 2,
        block: "D",
        description: "LABORATÓRIO DE BIOLOGIA V",
      },
      {
        room: "207",
        floor: 2,
        block: "D",
        description: "LABORATÓRIO DE BIOLOGIA VI",
      },
      {
        room: "208",
        floor: 2,
        block: "D",
        description: "COPA - CEDIDA PARA EMPRESA TERCEIRIZADA",
      },
      {
        room: "209",
        floor: 2,
        block: "D",
        description: "LABORATÓRIO DE QUÍMICA I",
      },
      {
        room: "210",
        floor: 2,
        block: "D",
        description: "LABORATÓRIO DE QUÍMICA II",
      },
      {
        room: "211",
        floor: 2,
        block: "D",
        description: "LABORATÓRIO DE QUÍMICA III",
      },
      {
        room: "212",
        floor: 2,
        block: "D",
        description: "CENTRAL ANALÍTICA",
      },
      {
        room: "213",
        floor: 2,
        block: "D",
        description: "LABORATÓRIO DE QUÍMICA IV",
      },
      {
        room: "214",
        floor: 2,
        block: "D",
        description: "LABORATÓRIO DE QUÍMICA V",
      },
      {
        room: "215",
        floor: 2,
        block: "D",
        description: "LABORATÓRIO DE QUÍMICA VI",
      },
      {
        room: "301",
        floor: 3,
        block: "D",
        description: "LABORATÓRIO DE FÍSICA I",
      },
      {
        room: "302",
        floor: 3,
        block: "D",
        description: "LABORATÓRIO DE FÍSICA II",
      },
      {
        room: "303",
        floor: 3,
        block: "D",
        description: "LABORATÓRIO DE FÍSICA III",
      },
      {
        room: "304",
        floor: 3,
        block: "D",
        description: "LABORATÓRIO DE MATEMÁTICA I",
      },
      {
        room: "305",
        floor: 3,
        block: "D",
        description: "LABORATÓRIO DE MATEMÁTICA II",
      },
      {
        room: "306",
        floor: 3,
        block: "D",
        description: "DEPÓSITO GERÊNCIA DE TECNOLOGIA DA INFORMAÇÃO",
      },
      {
        room: "307",
        floor: 3,
        block: "D",
        description: "LABORATÓRIO DE COMPUTAÇÃO I",
      },
      {
        room: "308",
        floor: 3,
        block: "D",
        description: "LABORATÓRIO DE COMPUTAÇÃO II",
      },
      {
        room: "309",
        floor: 3,
        block: "D",
        description: "LABORATÓRIO DE COMPUTAÇÃO III",
      },
      {
        room: "310",
        floor: 3,
        block: "D",
        description: "GERÊNCIA DE TECNOLOGIA DA INFORMAÇÃO",
      },
      {
        room: "311",
        floor: 3,
        block: "D",
        description: "LABORATÓRIO DE COMPUTAÇÃO VI",
      },
      {
        room: "312",
        floor: 3,
        block: "D",
        description: "LABORATÓRIO DE COMPUTAÇÃO VI",
      },
      {
        room: "313",
        floor: 3,
        block: "D",
        description: "LABORATÓRIO DE COMPUTAÇÃO VI",
      },
      {
        room: "101 A",
        floor: 1,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "101 B",
        floor: 1,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "101 C",
        floor: 1,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "101 D",
        floor: 1,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "101 E",
        floor: 1,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "102",
        floor: 1,
        block: "E",
        description: "SALA DE REUNIÃO",
      },
      {
        room: "103",
        floor: 1,
        block: "E",
        description: "ARQUIVO PERMANENTE ICET",
      },
      {
        room: "104 A",
        floor: 1,
        block: "E",
        description: "COORDENAÇÃO DE CURSO ENGENHARIA SANITÁRIA",
      },
      {
        room: "104 B",
        floor: 1,
        block: "E",
        description: "COORDENAÇÃO DE CURSO FARMÁCIA",
      },
      {
        room: "104 C",
        floor: 1,
        block: "E",
        description: "COORDENAÇÃO DE CURSO MATEMÁTICA E FÍSICA",
      },
      {
        room: "104 D",
        floor: 1,
        block: "E",
        description: "COORDENAÇÃO DE CURSO QUÍMICA INDUSTRIAL",
      },
      {
        room: "104 E",
        floor: 1,
        block: "E",
        description: "COORDENAÇÃO DE CURSO SISTEMA DE INFROMAÇÃO",
      },
      {
        room: "105 F",
        floor: 1,
        block: "E",
        description: "COORDENAÇÃO DE CURSO QUÍMICA E BIOLOGIA",
      },
      {
        room: "105 G",
        floor: 1,
        block: "E",
        description: "COORDENAÇÃO DE CURSO PÓS-GRADUAÇÃO",
      },
      {
        room: "105 H",
        floor: 1,
        block: "E",
        description: "COORDENAÇÃO DE CURSO AGRONIMIA",
      },
      {
        room: "105 I",
        floor: 1,
        block: "E",
        description: "COORDENAÇÃO DE CURSO ENGENHARIA DE PRODUÇÃO",
      },
      {
        room: "105 J",
        floor: 1,
        block: "E",
        description: "COORDENAÇÃO DE CURSO ENGENHARIA DE SOFTWARE",
      },
      {
        room: "106",
        floor: 1,
        block: "E",
        description: "COPA",
      },
      {
        room: "107",
        floor: 1,
        block: "E",
        description: "SALA DE LEITURA",
      },
      {
        room: "108",
        floor: 1,
        block: "E",
        description: "BIBLIOTECA",
      },
      {
        room: "201 A",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "201 B",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "201 C",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "201 D",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "201 E",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "201 F",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "202 A",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "202 B",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "202 C",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "202 D",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "202 E",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "202 F",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "203 A",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "203 B ",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "203 C",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "203 D",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "203 E",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "203 F",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "204 A",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "204 B",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "204 C",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "204 D",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "204 D",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "204 E",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "204 F",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "205",
        floor: 2,
        block: "E",
        description: "APOIO CADM",
      },
      {
        room: "206 A",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "206 B",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "206 C",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "206 D",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "206 E",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "206 F",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "207 A",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "207 B",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "207 C",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "207 D",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "207 E",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "207 F",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "208 A",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "208 B",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "208 C",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "208 D",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "208 E",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "208 F",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "209 A",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "209 B",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "209 C",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "209 D",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "209 E",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "209 F",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "210 A",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "210 B",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "210 C",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "210 D",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "210 E",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "210 F",
        floor: 2,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "211",
        floor: 2,
        block: "E",
        description: "SALA DE STUDOS PÓS-GRADUAÇÃO",
      },
      {
        room: "301 A",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "301 B",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "301 C",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "301 D",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "301 E",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "301 F",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "302 A",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "302 B",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "302 C",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "302 D",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "302 E",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "302 F",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "303 A",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "303 B ",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "303 C",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "303 D",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "303 E",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "303 F",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "304 A",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "304 B",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "304 C",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "304 D",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "304 D",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "304 E",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "304 F",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "305",
        floor: 3,
        block: "E",
        description: "APOIO CADM",
      },
      {
        room: "306 A",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "306 B",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "306 C",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "306 D",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "306 E",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "306 F",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "307 A",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "307 B",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "307 C",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "307 D",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "307 E",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "307 F",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "308 A",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "308 B",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "308 C",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "308 D",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "308 E",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "308 F",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "309 A",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "309 B",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "309 C",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "309 D",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "309 E",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "309 F",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "310 A",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "310 B",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "310 C",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "310 D",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "310 E",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "310 F",
        floor: 3,
        block: "E",
        description: "GABINETE DE PROFESSOR",
      },
      {
        room: "311",
        floor: 3,
        block: "E",
        description: "SALA DE ATENDIMENTO SERVIÇO DE PSICOLOGIA",
      },
      {
        room: "RECEPÇÃO",
        floor: 1,
        block: "F",
        description: "RECEPÇÃO BLOCO F",
      },
      {
        room: "1",
        floor: 1,
        block: "F",
        description: "APOIO CADM",
      },
      {
        room: "2",
        floor: 1,
        block: "F",
        description: "APOIO CADM",
      },
      {
        room: "3",
        floor: 1,
        block: "F",
        description: "APOIO CADM",
      },
      {
        room: "4",
        floor: 1,
        block: "F",
        description: "PROGRAMA DE ACESSIBILIDADE",
      },
      {
        room: "-",
        floor: 1,
        block: "F",
        description: "MEMORÁLIA",
      },
    ]);
  }
}
